### PR TITLE
Run the script out of the box on Windows

### LINKED ISSUE #23: Can not be executed on Windows 10
OS: Windows 10 Pro

Since I'm not a big fan of -g installs, I've created an empty npm project, and installed appium-doctor using
`npm install --save appium appium-doctor`

Then by adding appium-doctor in scripts section of package.json I'm able to execute.

But receiving this error:
```
TypeError: Cannot read property 'replace' of undefined
    at Function.retrieveUsingWhichCommand$ (X:\ondra\internal\appium-test\node_modules\appium-doctor\build\lib\node-detector.js:152:30)
    at tryCatch (X:\ondra\internal\appium-test\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (X:\ondra\internal\appium-test\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (X:\ondra\internal\appium-test\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (X:\ondra\internal\appium-test\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "appium-doctor"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! appium-test@1.0.0 appium-doctor: `appium-doctor`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-test@1.0.0 appium-doctor script 'appium-doctor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     appium-doctor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     \appium-test\npm-debug.log
```

Looking in the code I've noticed you can set NODE_BIN variable to skip all the automatic lookups for a node. It might be stated in the readme, as recommended on Windows.

There is also a one-liner to set the variable using Windows' `where`:
`for /f "delims==" %i in ('where node') do @set "NODE_BIN=%i"`

### PR DESCRIPTION
**Pull request by deep9**
Fixes #23

### CODE REVIEW

File: lib/node-detector.js [hunk 1]
```diff
@@ -26,7 +26,10 @@ class NodeDetector {
     let stdout;
     try {
       stdout = (await exec('which', ['node'])).stdout;
-    } catch (ign) {}
+    } catch (ign) {
```
Comment (imurchie) [inline lib/node-detector.js]: This should not be `ign` anymore (`ign` signifies "ignore"). Change to `err`.

File: lib/node-detector.js [hunk 2]
```diff
@@ -37,6 +40,24 @@ class NodeDetector {
     }
   }
 
+  static async retrieveUsingWhereCommand () {
```
Comment (imurchie) [inline lib/node-detector.js]: This is essentially the same as `retrieveUsingWhichCommand`, so repeating it is not particularly good. It would be better to change the name of a single method to something like `retrieveUsingSystemCall` and then inside, check if this is windows using `appium-support`:

```js
import { system } from 'appium-support';

let cmd = 'which';
if (system.isWindows()) {
  cmd = 'where';
}
stdout = (await exec(cmd, ['node'])).stdout;
```

File: lib/node-detector.js [hunk 3]
```diff
@@ -37,6 +40,24 @@ class NodeDetector {
...
+    if (await fs.exists(nodePath)) {
+      log.debug(`Node binary found using where command at: ${nodePath}`);
+      return nodePath;
+    } else {
+      log.debug('Node binary not found using the where command.');
+      return null;
+    }
+  }
+
   static async retrieveUsingAppleScript () {
```
Comment (imurchie) [inline lib/node-detector.js]: This method, then, should only be called on Mac systems (there not existing AppleScript anywhere else).

**Comment by imurchie** [comment]
Published in `appium-doctor@1.4.0`
